### ISSUE TITLE
5-1 checker BUG

### ISSUE THREAD

**Issue by ZihanYuanCN** [opendilab/LLMRiddles#10]
![微信截图_20231109010604](https://github.com/opendilab/LLMRiddles/assets/13405613/577b8dcc-9ec2-4ffd-849e-937d24f733d9)
题目要求的是“不包含”问题中的任意字符，而checker实际是在检测回答是否与问题一致
in [level5.py](https://github.com/opendilab/LLMRiddles/blob/main/llmriddles/questions/level5.py) line 50:

```
    if answer_text == user_text:
        return True, None
    else:
        return False, None
```

**Comment by PaParaZz1** [comment]
这个问题已经被开源贡献者 @cxumol 在 #11 中修复，并已合并到主分支
