### ISSUE TITLE
4-1错误返回文本不准确

### ISSUE THREAD

**Issue by Cwift** [opendilab/LLMRiddles#12]
4-1是要求同时包含输入数字+1和-1这两种情况, 但是输出文本是"回答中应该包含一个与问题相差1的数字", 应当改为"回答中应该包含所有与问题相差1的数字"

**Comment by TianyiPeng** [comment]
<img width="1313" alt="image" src="https://github.com/opendilab/LLMRiddles/assets/3522518/dccaa7a7-958e-4be6-bea9-a7aad3ef782f">

为什么这个会判错？而且解释 `Question should be a positive integer.` 也不对？

**Comment by zjowowen** [comment]
Thanks, we have fixed it in https://github.com/opendilab/LLMRiddles/pull/8
We will update huggingface space demo soon.
