### ISSUE TITLE
第四章第一题的bug

### ISSUE THREAD

**Issue by Ruanxingzhi** [opendilab/LLMRiddles#7]
![image](https://github.com/opendilab/LLMRiddles/assets/16996226/2fb21663-0d93-41cd-8f2b-9eb85e35dfb9)

修复方案（猜测）：`questions/level4.py` 第 85 行
```python
    if not check_if_is_number(question_text):
```
改为
```python
    if not check_if_is_number(question_text.strip()):
```

**Comment by PaParaZz1** [comment]
这个问题已在 #8 中被修复。
